### ISSUE TITLE
Personal pmdl

### ISSUE THREAD

**Issue by bimbim2401** [drftg/MMM-Assistant#2]
Hello

First of all thanks a lot for this works it a amazing

It works well with the Alexa hot word for assistant and smart mirror hotword for the mm

is there a time-out for the mm wake word when no command are recognize, it seem to stay blocked with a red mic icon

is it possible to have the same hotword for both, and when a command is not recognized it try with the assistant ?

I have record my personal pmdl for both ( mm and assistant), but when I launch the mm, it recognize immediately the assistant wake word despite I didn’t say nothing, do that two times and then understand the mm wake word despite I still have not said anything.

Can u please help me

**Comment by drftg** [comment]
@bimbim2401 

There is a timeout for both the assistant and the commander. I think around 90 seconds.
At this moment there is no fall back from the commander to the assistant. A possible solution would be to use the assistant for all commands. eouia started work on that but never completed.

From personal experience I can say that recording your own pmdl will result in lots of false positives. You can try tweaking the sensitivity in your config. I chose to use umdl's as much as possible.

**Comment by bimbim2401** [comment]
Ok thanks you
