### ISSUE TITLE
Installation of your version on the original eouia 

### ISSUE THREAD

**Issue by bimbim2401** [drftg/MMM-Assistant#3]
Hello

Do you have any advice for installing your module on eouia mmm-assistant. 
From scratch? Or just replace file ?

**Comment by drftg** [comment]
@bimbim2401 Just install is instead of eouia's version. 

`git clone https://github.com/eouia/MMM-Assistant.git`

and follow all the instructions of the original version

**Comment by bimbim2401** [comment]
Ok thanks you
